os: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib64-msvc-14.1

build: Script

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..
  - cmake --build . --config Release
