os: Visual Studio 2019

environment:
  BOOST_ROOT: C:\Libraries\boost_1_50_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_50_0\lib64-msvc-14.0

build: Script

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" ..
  - cmake --build . --config Release
